# Generated by Django 2.1.7 on 2019-08-14 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_b1', models.CharField(max_length=100)),
                ('child_fname', models.CharField(max_length=100)),
                ('child_mname', models.CharField(max_length=100)),
                ('child_lname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('type_of_birth', models.CharField(max_length=100)),
                ('other_type_of_birth', models.TextField(blank=True)),
                ('nature_of_birth', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('place_of_birth_sub_county', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_fname', models.CharField(max_length=100)),
                ('mother_mname', models.CharField(max_length=100)),
                ('mother_lname', models.CharField(max_length=100)),
                ('notified_name', models.CharField(max_length=50)),
                ('notified_id', models.CharField(max_length=100)),
                ('notified_date', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mcrh_Birth_Record.Parent'),
        ),
    ]
