# Generated by Django 2.1.7 on 2019-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcrh_Birth_Record', '0003_auto_20190814_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='other_type_of_birth',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
