# Generated by Django 2.1.7 on 2019-08-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mcrh_Birth_Record', '0004_auto_20190814_2117'),
        ('searches', '0002_auto_20190815_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='user',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mcrh_Birth_Record.Child'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=220),
        ),
    ]
